### ISSUE TITLE
[PUBLICATION] New publication

### ISSUE THREAD

**Issue by ytsrt66589** [mcomunita/AFX-Research#2]
Please fill as much info as possible:

[*] = required

- [*] Title: Hyper Recurrent Neural Network: Condition Mechanisms for Black-box Audio Effect Modeling 
- [*] Author(s): Yen-Tung Yeh, Wen-Yi Hsiao, and Yi-Hsuan Yang
- [*] URL: https://arxiv.org/abs/2408.04829
- [*] Date: 2024-08
- [*] Main Task: modeling
- Paradigm(s): Black-box
- [*] Device(s) Type(s): overdrive, compressor
- Device(s)s: Boss OD-3, Teletronix LA-2A
- Parametric/Controllable: Y
- [*] Neural/Differentiable: Y
- Method: Neural Network
- Webpage: https://yytung.notion.site/HyperRNN
- Code: https://github.com/ytsrt66589/pyneuralfx
- Dataset: https://drive.google.com/file/d/1y3iQH94dAZbRgP33Pt4lJakgolvV7Xal/view?usp=sharing
- [*] Abstract: Recurrent neural networks (RNNs) have demonstrated impressive results for virtual analog modeling of audio effects. These networks process time-domain audio signals using a series of matrix multiplication and nonlinear activation functions to emulate the behavior of the target device accurately. To additionally model the effect of the knobs for an RNN-based model, existing approaches integrate control parameters by concatenating them channel-wisely with some intermediate representation of the input signal. While this method is parameter-efficient, there is room to further improve the quality of generated audio because the concatenation-based conditioning method has limited capacity in modulating signals. In this paper, we propose three novel conditioning mechanisms for RNNs, tailored for black-box virtual analog modeling. These advanced conditioning mechanisms modulate the model based on control parameters, yielding superior results to existing RNN- and CNN-based architectures across various evaluation metrics.

**Comment by mcomunita** [comment]
Thanks for your contribution.
