### ISSUE TITLE
[PUBLICATION] New publication

### ISSUE THREAD

**Issue by ytsrt66589** [mcomunita/AFX-Research#3]
Please fill as much info as possible:

[*] = required

- [*] Title: DDSP Guitar Amp: Interpretable Guitar Amplifier Modeling
- [*] Author(s): Yen-Tung Yeh, Yu-Hua Chen, Yuan-Chiao Cheng, Jui-Te Wu, Jun-Jie Fu, Yi-Fan Yeh, Yi-Hsuan Yang
- [*] URL: https://arxiv.org/abs/2408.11405
- [*] Date: 2024-08
- [*] Main Task: modeling
- Paradigm(s): Gray-box
- [*] Device(s) Type(s): Amp
- Device(s)s: Marshall JVM 410H 
- Parametric/Controllable: Y
- [*] Neural/Differentiable: Y
- Method: Neural Network + Wiener-Hammersten 
- Webpage: https://ytsrt66589.github.io/ddspGuitarAmp_Demo/
- Code: 
- Dataset: 
- [*] Abstract: Neural network models for guitar amplifier emulation, while being effective, often demand high computational cost and lack interpretability. Drawing ideas from physical amplifier design, this paper aims to address these issues with a new differentiable digital signal processing (DDSP)-based model, called ``DDSP guitar amp,'' that models the four components of a guitar amp (i.e., preamp, tone stack, power amp, and output transformer) using specific DSP-inspired designs. With a set of time- and frequency-domain metrics, we demonstrate that DDSP guitar amp achieves performance comparable with that of black-box baselines while requiring less than 10% of the computational operations per audio sample, thereby holding greater potential for usages in real-time applications.

**Comment by mcomunita** [comment]
Thanks for your contribution
