### ISSUE TITLE
[PUBLICATION] New publication

### ISSUE THREAD

**Issue by RiccardoVib** [mcomunita/AFX-Research#4]
Please fill as much info as possible:

[*] = required

- [*] Title: Modeling Time-Variant Responses of Optical Compressors with Selective State Space Models
- [*] Author(s): Riccardo Simionato, Stefano Fasciani
- [*] URL: https://www.arxiv.org/abs/2408.12549
- [*] Date: 2024-09
- [*] Main Task: modeling
- Paradigm(s): Black-box
- [*] Device(s) Type(s): Compressors
- Device(s)s: Tubetech CL 1B, Teletronix LA-2A
- Parametric/Controllable: Y
- [*] Neural/Differentiable: Y
- Method: Neural Network
- Webpage: https://riccardovib.github.io/Optical-DRC-SSM_pages/
- Code: https://github.com/RiccardoVib/Optical-DRC-with-Selective-SSMs
- Dataset: (https://www.kaggle.com/datasets/riccardosimionato/optical-dynamic-range-compressors-la-2a-cl-1b/versions/1)
- [*] BibTex: 
@misc{simionato2024modelingtimevariantresponsesoptical,
      title={Modeling Time-Variant Responses of Optical Compressors with Selective State Space Models}, 
      author={Riccardo Simionato and Stefano Fasciani},
      year={2024},
      eprint={2408.12549},
      archivePrefix={arXiv},
      primaryClass={cs.SD},
      url={https://arxiv.org/abs/2408.12549}, 
}
- [*] Abstract:
This paper presents a method for modeling optical dynamic range compressors using deep neural networks with Selective State Space models. The proposed approach surpasses previous methods based on recurrent layers by employing a Selective State Space block to encode the input audio. It features a refined technique integrating Feature-wise Linear Modulation and Gated Linear Units to adjust the network dynamically, conditioning the compression's attack and release phases according to external parameters. The proposed architecture is well-suited for low-latency and real-time applications, crucial in live audio processing. The method has been validated on the analog optical compressors TubeTech CL 1B and Teletronix LA-2A, which possess distinct characteristics. Evaluation is performed using quantitative metrics and subjective listening tests, comparing the proposed method with other state-of-the-art models. Results show that our black-box modeling methods outperform all others, achieving accurate emulation of the compression process for both seen and unseen settings during training. We further show a correlation between this accuracy and the sampling density of the control parameters in the dataset and identify settings with fast attack and slow release as the most challenging to emulate.

**Comment by mcomunita** [comment]
Thanks for your contribution!
