### ISSUE TITLE
[PUBLICATION] HYBRID NEURAL AUDIO EFFECTS

### ISSUE THREAD

**Issue by RiccardoVib** [mcomunita/AFX-Research#5]
Please fill as much info as possible:

[*] = required

- [*] Title: HYBRID NEURAL AUDIO EFFECTS
- [*] Author(s): Riccardo Simionato, Stefano Fasciani
- [*] URL: (https://smcnetwork.org/smc2024/papers/SMC2024_paper_id82.pdf)
- [*] Date: 2024-07
- [*] Main Task: modeling
- Paradigm(s): Black-box
- [*] Device(s) Tape recorder,  preamplifier, compressor
- Device(s)s: Akai 4000D open reel tape recorder, Universal Audio 6176 Channel Strip limiter amplifier 1176LN, Tubetech CL 1B
- Parametric/Controllable: Y
- [*] Neural/Differentiable: Y
- Method: Neural Network
- Webpage: (https://riccardovib.github.io/Hybrid-Neural-Audio-Effects_pages/)
- Code: (https://github.com/RiccardoVib/Hybrid-Neural-Audio-Effects)
- Dataset: preamplifier: (https://zenodo.org/records/3562442), compressor: https://www.kaggle.com/datasets/riccardosimionato/tubetech-cl-1b, tape: https://zenodo.org/records/8026272
- [*] BibTex: @article{simionato2024hybrid,
  title={HYBRID NEURAL AUDIO EFFECTS},
  author={SIMIONATO, Riccardo and FASCIANI, Stefano},
  booktitle={Proceedings of the International Conference on Sound and Music Computing},
  year={2024}}
- [*] Abstract: Machine learning techniques are commonly employed for modeling audio devices, particularly analog audio effects.
Conditioned models have been proposed as well. The conditioning mechanism utilizes the control parameters of the modeled device to influence the sound alteration process. Neural networks are shown to be capable of interpolating between conditioning parameter values. This paper further investigates the interpolation ability of neural audio effects. In particular, we introduce additional conditioning parameters to instruct the neural network to learn and predict different audio effects using Feature-wise Linear Modulation and the Gated Linear Unit. The resulting model is a hybrid neural effect that can reproduce, depending on the
conditioning values, the audio-altering process of a specific audio effect or interpolates between them. We created hybrid audio effects from a preamp circuit, an optical compressor, and a tape recorder. The designed models are able to learn the sound alteration processes for individual effects and their combinations without producing audible artifacts, and users can use the conditioning parameters to navigate in a continuous space where each point represents a different hybrid audio effect.

**Comment by mcomunita** [comment]
Thanks for your contribution!
