### ISSUE TITLE
[PUBLICATION] Conditioning Methods for Neural Audio Effects

### ISSUE THREAD

**Issue by RiccardoVib** [mcomunita/AFX-Research#6]
Please fill as much info as possible:

[*] = required

- [*] Title: Conditioning Methods for Neural Audio Effects
- [*] Author(s): Riccardo Simionato, Stefano Fasciani
- [*] URL: (https://smcnetwork.org/smc2024/papers/SMC2024_paper_id83.pdf)
- [*] Date: in the 2024-07
- [*] Main Task: modeling
- Paradigm(s): Black-box
- [*] Device(s) Type(s): overdrive, compressor
- Device(s)s: FabFilter Pro C2, SphereComp,  Auditory Dr Drive, Otto8 Overdrive (OD2) 
- Parametric/Controllable: Y
- [*] Neural/Differentiable: Y
- Method: Neural Network
- Webpage: (https://riccardovib.github.io/Conditioning-Methods-for-Neural-Audio-Effects_pages/)
- Code: https://github.com/RiccardoVib/Conditioning-Methods-for-Neural-Audio-Effects
- Dataset: https://www.kaggle.com/datasets/riccardosimionato/compressor-and-overdrive-audio-effect-datasets
- [*] BibTex: @article{simionato2024hybrid,
  title={Conditioning Methods for Neural Audio Effects},
  author={Simionato, Riccardo and Fasciani, Stefano},
  booktitle={Proceedings of the International Conference on Sound and Music Computing},
  year={2024}
}
- [*] Abstract: Machine learning techniques have become a common approach for modeling analog audio effects. Black-box and hybrid solutions have been applied to a large variety of audio effects. Audio effects usually incorporate user-controllable parameters, and how to infuse this information into the networks is still a challenge. Feature-wise Linear Modulation is a popular conditioning method, but its use in audio effect modeling is still limited. This technique involves an affine transformation via learnable coefficients based on conditioning information. This study compares this approach with other proposals used in this field, such as gated activation. In addition, the control parameters may present a nonlinear relationship with the effect’s associated sonic response. Therefore, the investigation also considers nonlinear mapping. This case study investigates two types of analog audio effects: distortion and dynamic range compression. Results indicate the conditioning layer leads to better performance if placed at the end of the architecture, and the Feature-wise Linear Modulation method outperforms other approaches. In addition, nonlinear mapping can be beneficial for cases with strong nonlinear relationships between parameters, such as the overdrive effect.

**Comment by mcomunita** [comment]
Done!
